sudo: required
language: python
python:
- 3.5.2

addons:
  apt:
    packages:
    - sshpass
services:
- docker

branches:
- master
- develop
- "/^pr\\..*/"
- "/^release\\..*/"

before_install:
- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
  -in secrets.tar.enc -out ./secrets.tar -d
- tar xvf secrets.tar
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
- docker --version

install:
- docker images

script:
- sed -i 's/DEBUG\ =\ True/DEBUG\ =\ False/g' app/uksHub/settings.py #turn off debug option for django
- docker-compose build --build-arg DEPLOY=1 web
- docker-compose up -d
- docker exec uksprojekat_web_1 python3 manage.py test -v2

after_success:
- docker tag uksprojekat_web "$DOCKER_USERNAME"/ukshub:production
- docker push $DOCKER_USERNAME/ukshub:production
- export SSHPASS=$DEPLOY_PASS

deploy:
  provider: script
  skip_cleanup: true
  script: chmod 600 deploy_key && sshpass -e ssh -o StrictHostKeyChecking=no -i ./deploy/deploy_key
    $HOST@$HOST_IP './deploy.sh'
  on:
    branch: master
