sudo: required
language: python
python:
  - '3.5.2'

addons:
  apt:
    packages:
    - sshpass
services:
  - docker

before_install:
  - docker --version
  - ls
  - docker-compose -p $DOCKER_USERNAME/ukshub:latest build .
  - docker images

install:
  - pip install -r requirements/requirements.txt

script:
  - docker exec web "python manage.py test project/tests"

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/ukshub:latest
  - export SSHPASS=$DEPLOY_PASS
