sudo: required
language: python
python:
- 3.5.2
addons:
  apt:
    packages:
    - sshpass
services:
- docker
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
  -in deploy_key.enc -out ./deploy_key -d
- docker --version
- openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv
  -in postgres.env.enc -out app/postgres.env -d
install:
- docker-compose -p "$DOCKER_USERNAME"/ukshub:latest build --build-arg DEPLOY=1 web
- docker images
script:
- docker-compose up -d
- docker exec uksprojekat_web_1 python3 manage.py test -v2
after_success:
- docker push $DOCKER_USERNAME/ukshub:latest
branches:
- master
- develop
- "/^pr\\..*/"
- "/^release\\..*/"
